name: theme_builder
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/theme_builder/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
